### ISSUE TITLE
Extension doesn't load on vanilla Revit 2023 VM

### ISSUE THREAD

**Issue by twastvedt** [DynamoDS/DynamoGraphUpdater#16]
Maybe I'm missing something super obvious (hope so!). I have a vanilla Revit 2023 VM (with GD). I downloaded the latest release (0.0.6), copied it to %AppData%\Dynamo\Dynamo Revit\2.13\packages, and started Dynamo. No menu item under Extensions, and I get the following in the log file:
```
2023-05-31 17:50:59Z : Could not create an instance of DynamoGraphMigrationAssistant.DynamoGraphMigrationAssistantViewExtension
2023-05-31 17:50:59Z : Exception has been thrown by the target of an invocation.
2023-05-31 17:50:59Z :    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Dynamo.Wpf.Extensions.ViewExtensionLoader.Load(ViewExtensionDefinition viewExtension)
```

**Comment by twastvedt** [comment]
It does load in Revit 2024 which I have installed locally. Is it working in Revit 2023 elsewhere?

**Comment by johnpierson** [comment]
Hmm are the DLLs blocked by chance?

**Comment by johnpierson** [comment]
I have only really tested in sandbox so far. Let me check it out too.

**Comment by twastvedt** [comment]
> Hmm are the DLLs blocked by chance?

Not blocked

**Comment by johnpierson** [comment]
Just tested in Revit 2023 on my end. Do you have the point release? As I noticed I am in 2.16.1 and yours is showing 2.13
![image](https://github.com/DynamoDS/DynamoGraphMigrationAssistant/assets/15744724/994110f4-346c-407c-a9e1-b0720c40dd58)

**Comment by twastvedt** [comment]
Ah, ok. Yes, it works in 2023.1, but not in 2023 (for me).

**Comment by johnpierson** [comment]
Was file trust added in 2.16? I’m using those methods now so I’m wondering
if that’s why

**Comment by twastvedt** [comment]
Looks like it: https://help.autodesk.com/view/RVT/2023/ENU/?guid=RevitDynamo_Whats_New_in_Dynamo_for_Revit_html. Not sure if this is intended to work with 2023.0 or not, maybe we just need a note that it won't.

**Comment by johnpierson** [comment]
Ah that is it then. We will have to see what we want to do. Generally, people should be in the point release as the initial 2023 release had breaking bugs in it.
